services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: PostgreSQLPass@2025
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped
  mail_dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo
  bsn-api:
    container_name: bsn-api
    image: ${DOCKER_USERNAME}/bsn-api:${APP_VERSION}
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book_social_network_db
      EMAIL_HOST_NAME: ${EMAIL_HOST_NAME}
      EMAIL_USER_NAME: ${EMAIL_USER_NAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    ports:
      - "8088:8088"
    networks:
      - spring-demo
    depends_on:
      - postgres
      - mail_dev


networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local